language: node_js
node_js:
  - "8"
install:
  - npm install
cache:
  directories:
    - "node_modules"
before_deploy:
  echo "Before deploy..."
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: /docs
  github_token: $GH_TOKEN
  committer-from-gh: true
script:
  - npm test
  - npm run danger-ci
after_success:
  - npm run report-coverage
  - npx semantic-release
  - npm run build:docs