language: node_js
node_js:
  - "8"
install:
  - npm install
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: /docs
  github_token: $GH_TOKEN
script:
  - npm test
  - npm run danger-ci
after_success:
  - npm run report-coverage
  - npx semantic-release