language: node_js
node_js:
  - "8"
install:
  - npm install
cache:
  directories:
    - "node_modules"
before_deploy:
  - npm run build:docs
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: /docs
  github_token: $GH_TOKEN
  edge:
    branch: v1.8.47
script:
  - npm test
  - npm run danger-ci
after_success:
  - npm run report-coverage
  - npm run build
  - npx semantic-release